# Generated by Django 5.1.1 on 2024-11-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('plant', models.CharField(max_length=70)),
                ('scientific_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('habitat', models.CharField(max_length=90)),
                ('care_instructions', models.TextField(max_length=90)),
                ('average_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
