# Generated by Django 5.1.1 on 2024-11-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
    ]
