# Generated by Django 5.1.3 on 2024-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='gmail',
            field=models.EmailField(default='edwinvega3106@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
