# Generated by Django 5.1.3 on 2024-11-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_delete_createuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gmail',
        ),
    ]
